### ISSUE TITLE
Produkty Lakto

### ISSUE THREAD

**Issue by devillante** [devillante/sorryjako#6]
Dobrý den, na Rohlik.cz jsou i produkty, které nepatří přímo do značek koncernu, ale koncern je vyrábí a možná z důvodu nepřímého uvedení značky nejsou rozšířením skryty - např. Lakto Trvanlivé mléko polotučné 1,5% - Adresa výrobce: Mlékárna Hlinsko, a.s. Kouty 53 539 01 Hlinsko Česká republika, neboli Tatra.

**Comment by janbinderibm** [comment]
#10

**Comment by devillante** [comment]
Merged
