### ISSUE TITLE
Produkty firmy Ecoproduct

### ISSUE THREAD

**Issue by devillante** [devillante/sorryjako#7]
produkt na kosik.cz Ecoproduct Bio hovězí ořech (cca 500g)

se ukazuje jako od AB, nicmene ostatni produkty firmy ecoproduct 
nikoliv. Bud je tedy dle meho nazoru chyba v zarazeni produktu vyse, 
nebo v ne zarazeni ostanich produktu

**Comment by janbinderibm** [comment]
Opraveno veškeré maso na kosik.cz
#9

**Comment by devillante** [comment]
Merged.
